"""add ondelete SET NULL to analysis job_description_id

Revision ID: 976093c1b219
Revises: 34cad63c84a2
Create Date: 2026-09-15 16:52:14.293896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976093c1b219'
down_revision: Union[str, Sequence[str], None] = '34cad63c84a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('analyses_job_description_id_fkey'), 'analyses', type_='foreignkey')
    op.create_foreign_key(None, 'analyses', 'job_descriptions', ['job_description_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.create_foreign_key(op.f('analyses_job_description_id_fkey'), 'analyses', 'job_descriptions', ['job_description_id'], ['id'])
    # ### end Alembic commands ###
